language: node_js
node_js:
- '6'
- '7'
before_script:
- npm run build
after_success:
- npm run coveralls
deploy:
  skip_cleanup: true
  provider: npm
  email: info@molecuel.org
  api_key:
    secure: JbSEchzP8P13txyA1BhCr38FVGdsyFkZKmiXSv/1kVxH8tQMRLaWGdit96K41Vql8kla5MhoxeaKeGYvOvqFNQxVTMKbZvxxkCaD2vfFZJKJY18FjFfBWd3v3t0e0JghZEgmPgGpo9691pwVYMssBhRklOev9GtlHTNFtDrfuN9dcT/ligImx44bGyNvXEouGKng98RvDqvJgB4cSRaMRylAkjYZfn7x4tEvQJ0Ndbo88vOaFsoCk7LCbR7egBuQMrwtLuogyziUuKMCCnVfvxbrJE9W86tcorkTetdwB1HQGYfcRpWYzgNtc8Ltp2BTbufLTaVEbmBYcFxNq2OO2VZtmLuz3pZGnImAsExVU3swr7rQ9NL8dChIKgMPFhc88rVcpkZnbqQ1QG66UCHmaezMCILpqmcy2I1AAYKYc0SWhWLiS2lFCULv3eevsOp3RFbMIlepyGX+/gLJ6aydBFEr/6rwmPkSIbqSAyr6OP205S6gh8Jtb+FwJLbHhofrGLfhVNOCgUFgvZasC+aFzsJZkVyfJLf2nq6vxytc9M2R50eDTH7s64mVTPJHOE7F2U5o1/fARhtMI30wZ5aOU9zx3eB3HCXpQ6kaMljrPCCCedzrF2CoZyIwFS6YS1iLV8d5FooINxOVXel+kqEbaxRX8DOprkJCMkuyuxN+LXE=
  on:
    repo: molecuel/tsvalidate
