language: node_js
node_js:
- '6'
- '7'
before_script:
- npm run build
after_success:
- npm run coveralls
deploy:
  skip_cleanup: true
  provider: npm
  email: info@molecuel.org
  api_key:
    secure: BoAz2T49vn0FGOjxcjkhw+M5YwBnhcUfV0djckmYZtnkXWsZRZR2kH/6a3FTKF4Tf7RByfTgELElgpUKlFoAi8H1hRRXQA39UUsJ/dp8RCETBvIH3nUl0rX049ZPjTutJARX3JTqORt4PIU/r4AbZsm9HDcKPIFar6al8wGI4MdU93M3vE9qgMDUIZSqMFHKcOtFtZ7r2iDgBX/221otuqkoU+n5WmUc1qHNrsjo522WPGpEJRufIB7gqFi9LjSBXbwKVLdvF6u5ZYT2dDOd4dlZ6pSpujTjJylSdHy2JH9B96IBFv1ti8enDzTI5fQyH42K2v4srRVhdbszZiDC85Vtv5GMVjYnVYo0EJlSlC55I68JrscbAqu8x6S47l3VI1URJYpardzB5Nrzn94mFSzHEd2MQ+z5sfY+OICR0NWqLJ3K5HXsmN43UZmSKXNVdWsuWBuEWFRBaZybkimDzaYBr8bMuElL9uPe6MaWxZSCpV0NawX8FMzsYqRJ4TcMf8fOu8+LRAG2EduFeesPFVKmDiVTxX/el9HfEdBz5qwNsLPjmBDTXnGvcxA7Z2TOmVyfQ679WtC5zcp1cEqvkNLBVuK0a/zUtVfxvLdJ7Xh2HLRBk1EwUDb4BUZQmVeJqEE8d0jnrzX61Q6Njcru2SttTY4fr3HlD7RR7UX7jZc=
  on:
    repo: molecuel/tsvalidate
