language: node_js
node_js:
- '6'
- '7'
before_script:
- npm run build
after_success:
- npm run coveralls
deploy:
  skip_cleanup: true
  provider: npm
  email: info@molecuel.org
  api_key:
    secure: R5jMAQuhytu/OO3hkuXBFnjKCNsFP+ISLB0jUBOFZelb88R3sjoUXPNQ7y2KlMu9hOQBQT2n1yUHW70ud2cHx8oIfxi1EZnYaijkMyLaq3OLMKPTIOUPi5dGUZIojphWg22ym1wSYdWFEiKhm+SB36JtTLCPvQPwR3lmfUWMp73Uyc+U1nShlnTUpE3v84s5SuD90GVQ62+s5FN4twIwU9+YEw+0Y4JOLqTinuroG2QZZI5Yngm2rvOvVJLWhXoFPWQsL7HAQ4Zua53t4IcFkaAJ+vf0zX+CmosU2u5pjkDALVpxXIMKzZEiUd6R/c1Rf2JFIrw9s//hXVCmpPgHit4UgpLIt8tvdry0L5FaBZeW5yoems9/HGfr57Lh1rdk8k/UeJGIFlx1IpMZJdHrm+WnVNjl3dEU7gQfzfKFhJFaCqrbo+/Ap8/6F2DWukPb2KlUXNpa6AQXiYHUoFFpgEGUVuEuqKHFG/knlEhirRiuhT0Vdd3DY8gy/vMmIXNhe1KAbwk3cTrrZdH3rXgLn/kEn+tR/Ah/IAw8CKkgBILgH7mDoh9UfRxuJ2RylyESMfQdjN4Oj4RBxJot+LVQ4yI5hgveiaTGo7drhluAUBuVfGj7JB2iopjbc3iyRRKlETjoSCFHX5eW10kSfZBvKNF+oWoTvElloXb8xQODM7Y=
  on:
    repo: molecuel/tsvalidate
