language: node_js
node_js:
  - "4"
  env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
services:
  - mongodb
  - elasticsearch
before_script:
  - sleep 10
  - npm install -g gulp
  script: gulp
